name: licenses

on:
  schedule:
    - cron: "55 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: licenses
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - uses: actions/checkout@v2
    
    - name: licenses
      run: python ./Scripts/AckAck/ackack.py

    - name: Get Current Time
      uses: josStorer/get-current-time@v2.0.0
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+09:00"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: update licenses to Setting.bundle at ${{ env.TIME }}
        committer: Elon Park <dev.sungwoon@gmail.com>
        author: Elon Park <dev.sungwoon@gmail.com>
        title: AckAck - update licenses at ${{ env.TIME }}
        body: This pull request was initiated at ${{ env.TIME }}
        branch: update-licenses
        assignees: ${{ github.actor }}
        labels: documentation
      env:
        TIME: "${{ steps.current-time.outputs.formattedTime }}"